#!/usr/bin/env node
/**
 * Writes ui/.env.production from API_BASE_URL.
 *
 * Used by Cloudflare Pages (and other static hosts) before `vite build`.
 * Vite reads `.env.production` at build time and bakes VITE_* variables
 * into the JavaScript bundle.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const apiBaseUrl = process.env.API_BASE_URL?.trim();
if (!apiBaseUrl) {
  console.error('write-ui-env: API_BASE_URL is required (e.g. https://your-api.onrender.com/api)');
  process.exit(1);
}

const normalized = apiBaseUrl.replace(/\/$/, '');
const target = join(dirname(fileURLToPath(import.meta.url)), '../ui/.env.production');

const contents = `# Generated by scripts/write-ui-env.mjs — do not edit on deploy hosts.
VITE_API_URL=${normalized}
`;

writeFileSync(target, contents, 'utf8');
console.log(`write-ui-env: wrote ${target}`);
